
###Audio message testing##
#- alias: audio message testing
#  trigger:
#    - platform: time
#      at: '12:00:00'
#  action:
#    - service: tts.google_say
#      entity_id: media_player.living_room_speaker
#      data:
#        message: 'Audio message test'

###Sensible Google Mini Volumes###
- alias: volume down
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room_speaker
        - media_player.bedroom_speaker
      data:
        volume_level: "0.09"

- alias: volume wake up
  trigger:
    - platform: time
      at: '06:30:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.bedroom_speaker
      data:
        volume_level: "0.15"        
        
- alias: volume up
  trigger:
    - platform: time
      at: '08:30:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room_speaker
        - media_player.bedroom_speaker
      data:
        volume_level: "0.3"      

###Morning Alarms###
#- alias: Morning Radio
#  trigger:
#    - platform: time
#      at: '06:45:00'
#  condition:
#    - condition: time
#      weekday:
#        - mon
#        - tue
#        - wed
#        - thu
#        - fri
#  action:
#    - service: media_player.play_media
#      data_template:
#        volume: 0.15
#        entity_id:
#          - media_player.bedroom_speaker
#        media_content_id:
#          http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p
#        media_content_type: 'audio/mp4'

- alias: Wake-up Time
  trigger:
    - platform: time
      at: '07:06:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data_template:
        message: 'Good morning Amy & Bill. The Weather forecast is {{states.sensor.dark_sky_hourly_summary.state}}, the temperature outside is currently {{states.sensor.weather_temperature.state|round}} degrees, Amys travel time to work currently is {{states.sensor.amy_home_to_work.state}} minutes. Bills travel time to work currently is {{states.sensor.bill_home_to_work.state}} minutes. Time to get in the shower!'


### Home time###
- alias: Home time
  trigger:
    - platform: state
      entity_id: device_tracker.amysiphone
      to: 'home'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      after: '16:00:00'
      before: '18:15:00'
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/power"
        payload: "ON"
    - service: tts.google_say
      entity_id: media_player.living_room_speaker
      data:
        message: 'Welcome home Amy!'
        delay: '00:05:00'
      

- alias: Home time end dumb
  trigger:
    - platform: time
      at: '19:30:00'
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/power"
        payload: "OFF"
#- alias: Home time end smart
#  trigger:
#    - platform: state
#      entity_id: 

###Living Room Lamp###
- alias: Lamp light on
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  condition:
    - condition: state
      entity_id: device_tracker.bill_honor_7
      state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_lamp

- alias: Lamp light off
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_lamp

###Cat Heater Schedule###
- alias: Cat AM ON
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      below: 10
  action:
    - service: switch.turn_on
      entity_id: switch.space_heater
- alias: Cat AM OFF
  trigger:
    platform: time
    at: '08:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.space_heater
- alias: Cat PM ON
  trigger:
    platform: time
    at: '15:30:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      below: 10
  action:
    - service: switch.turn_on
      entity_id: switch.space_heater
- alias: Cat PM OFF
  trigger:
    platform: time
    at: '16:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.space_heater

  ##############################################################################
###  Take Snapshot at 2am and upload to dropbox at 4am
##############################################################################

#################################################################
## Snapshot
#################################################################

- alias: Snapshot
  trigger:
    platform: time
    at: '02:00:00'
  condition:
  - condition: time
    weekday:
      - sun
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}

#################################################################
## Dropbox upload using "Dropbox Sync" by dwelch2102
#################################################################

- alias: Snapshot Upload dropbox
  trigger:
    platform: time
    at: '04:00:00'
  action:
  - service: hassio.addon_stdin
    data_template:
      addon: 7be23ff5_dropbox_sync
      input: {"command":"upload"}
  
