###Conventional Sensors Go Here###

#Weather prediction
- platform: yr
  name: Weather
  icon: mdi:weather-partlycloudy
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: darksky
  api_key: !secret dark_sky_api_key
  units: uk2
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - hourly_summary
    - temperature
    - precip_probability
    - wind_speed
    - temperature_min  


- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: google_travel_time
  name: Bill Home to Work
  api_key: !secret gtt_api_key
  origin: !secret home_addr
  destination: !secret Bwork_addr

- platform: google_travel_time
  name: Amy Home to Work
  api_key: !secret gtt_api_key
  origin: !secret home_addr
  destination: !secret Awork_addr

- platform: waze_travel_time
  name: Bill Waze to Work
  origin: !secret home_addr
  destination: !secret Bwork_addr
  region: 'EU'

- platform: waze_travel_time
  name: Amy Waze to Work
  origin: !secret home_addr
  destination: !secret Awork_addr
  region: 'EU'
