  ##############################################################################
###  Take Snapshot at 2am and upload to dropbox at 4am
##############################################################################

#################################################################
## Snapshot
#################################################################

- alias: Snapshot
  trigger:
    platform: time
    at: '02:00:00'
  condition:
  - condition: time
    weekday:
      - sun
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}

#################################################################
## Dropbox upload using "Dropbox Sync" by dwelch2102
#################################################################

- alias: Snapshot Upload dropbox
  trigger:
    platform: time
    at: '04:00:00'
  action:
  - service: hassio.addon_stdin
    data_template:
      addon: 7be23ff5_dropbox_sync
      input: {"command":"upload"}
 
