###Audio message testing##
#- alias: audio message testing
#  trigger:
#    - platform: time
#      at: '12:00:00'
#  action:
#    - service: tts.google_say
#      entity_id: media_player.living_room_speaker
#      data:
#        message: 'Audio message test'
