###Sensible Google Mini Volumes###
- alias: volume down
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room_speaker
        - media_player.bedroom_speaker
      data:
        volume_level: "0.09"

- alias: volume wake up
  trigger:
    - platform: time
      at: '06:30:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.bedroom_speaker
      data:
        volume_level: "0.15"        
        
- alias: volume up
  trigger:
    - platform: time
      at: '08:30:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room_speaker
        - media_player.bedroom_speaker
      data:
        volume_level: "0.3"      

